language: python
branches:
    only:
    - master
    - dev
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
python:
  - "3.6"
  - "3.7"
  - "3.8"
# must turn off warnings becuase otherwise the travis log file gets too long
script: coverage run -m pytest -p no:warnings
after_success: bash <(curl -s https://codecov.io/bash)

