name: jet-tools
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - jedi=0.17.2
  - jupyter_console
  - setuptools
  - uproot=3.10.12
  - awkward=0.13.0
  - numpy
  - pandas
  - matplotlib
  - ipdb>=0.12.3
  - scipy
  - networkx>=2.4
  - pydot>=1.4.1
  - tabulate>=0.8.6
  - pytorch>=1.3.1
  - bokeh>=1.4.0
  - psutil>=5.6.7
  - pygit2>=1.2.1
  - pytz
  - hepunits
  - joblib
  - threadpoolctl
  - scikit-learn
  - pip:
    - sklearn
    - scikit-hep == 0.5.1
