name: Run python tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install python3
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6
            - name: Install dependancies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest
                  pip install coverage
            - name: Run tests with pytest
              run: coverage run -m pytest -p no:warnings
